/**
 * Helpers for box invite codes, generated by box-admin as 5 chars + "-" + 3
 * chars (e.g. "4KJ9P-XY2") and matched verbatim (dash included) by the
 * redeem endpoint.
 */

const CODE_PREFIX_LENGTH = 5;
const CODE_SUFFIX_LENGTH = 3;
const CODE_LENGTH = CODE_PREFIX_LENGTH + CODE_SUFFIX_LENGTH;

/**
 * Normalizes a box code as the athlete types or pastes it: strips anything
 * that isn't a letter/digit, uppercases it, and (re)inserts the "-" after
 * the 5th character. Works the same whether the dash was already there
 * (pasting the full code) or not (typing it by hand).
 */
export function formatBoxCodeInput(raw: string): string {
  const stripped = raw
    .toUpperCase()
    .replace(/[^A-Z0-9]/g, '')
    .slice(0, CODE_LENGTH);
  if (stripped.length <= CODE_PREFIX_LENGTH) return stripped;
  return `${stripped.slice(0, CODE_PREFIX_LENGTH)}-${stripped.slice(CODE_PREFIX_LENGTH)}`;
}
