/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminClassesRouteImport } from './routes/_authenticated/_admin/classes'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/_admin/dashboard'
import { Route as AuthenticatedAdminFinancesRouteImport } from './routes/_authenticated/_admin/finances'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/_admin/members'
import { Route as AuthenticatedAdminClassDetailIdRouteImport } from './routes/_authenticated/_admin/class-detail.$id'
import { Route as AuthenticatedAdminMemberDetailIdRouteImport } from './routes/_authenticated/_admin/member-detail.$id'
import { Route as AuthenticatedAdminMemberProfileIdRouteImport } from './routes/_authenticated/_admin/member-profile.$id'
import { Route as AuthenticatedAdminMoreIndexRouteImport } from './routes/_authenticated/_admin/more/index'
import { Route as AuthenticatedAdminMoreCoachesRouteImport } from './routes/_authenticated/_admin/more/coaches'
import { Route as AuthenticatedAdminMoreFilesRouteImport } from './routes/_authenticated/_admin/more/files'
import { Route as AuthenticatedAdminMoreInvitesRouteImport } from './routes/_authenticated/_admin/more/invites'
import { Route as AuthenticatedAdminMoreMyProfileRouteImport } from './routes/_authenticated/_admin/more/my-profile'
import { Route as AuthenticatedAdminMoreNotificationsRouteImport } from './routes/_authenticated/_admin/more/notifications'
import { Route as AuthenticatedAdminMorePlansRouteImport } from './routes/_authenticated/_admin/more/plans'
import { Route as AuthenticatedAdminMoreReportsRouteImport } from './routes/_authenticated/_admin/more/reports'
import { Route as AuthenticatedAdminMoreSettingsRouteImport } from './routes/_authenticated/_admin/more/settings'
import { Route as AuthenticatedAdminMoreWodRouteImport } from './routes/_authenticated/_admin/more/wod'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminClassesRoute =
  AuthenticatedAdminClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinancesRoute =
  AuthenticatedAdminFinancesRouteImport.update({
    id: '/finances',
    path: '/finances',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClassDetailIdRoute =
  AuthenticatedAdminClassDetailIdRouteImport.update({
    id: '/class-detail/$id',
    path: '/class-detail/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMemberDetailIdRoute =
  AuthenticatedAdminMemberDetailIdRouteImport.update({
    id: '/member-detail/$id',
    path: '/member-detail/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMemberProfileIdRoute =
  AuthenticatedAdminMemberProfileIdRouteImport.update({
    id: '/member-profile/$id',
    path: '/member-profile/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMoreIndexRoute =
  AuthenticatedAdminMoreIndexRouteImport.update({
    id: '/more/',
    path: '/more/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMoreCoachesRoute =
  AuthenticatedAdminMoreCoachesRouteImport.update({
    id: '/more/coaches',
    path: '/more/coaches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMoreFilesRoute =
  AuthenticatedAdminMoreFilesRouteImport.update({
    id: '/more/files',
    path: '/more/files',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMoreInvitesRoute =
  AuthenticatedAdminMoreInvitesRouteImport.update({
    id: '/more/invites',
    path: '/more/invites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMoreMyProfileRoute =
  AuthenticatedAdminMoreMyProfileRouteImport.update({
    id: '/more/my-profile',
    path: '/more/my-profile',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMoreNotificationsRoute =
  AuthenticatedAdminMoreNotificationsRouteImport.update({
    id: '/more/notifications',
    path: '/more/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMorePlansRoute =
  AuthenticatedAdminMorePlansRouteImport.update({
    id: '/more/plans',
    path: '/more/plans',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMoreReportsRoute =
  AuthenticatedAdminMoreReportsRouteImport.update({
    id: '/more/reports',
    path: '/more/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMoreSettingsRoute =
  AuthenticatedAdminMoreSettingsRouteImport.update({
    id: '/more/settings',
    path: '/more/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMoreWodRoute =
  AuthenticatedAdminMoreWodRouteImport.update({
    id: '/more/wod',
    path: '/more/wod',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/classes': typeof AuthenticatedAdminClassesRoute
  '/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/finances': typeof AuthenticatedAdminFinancesRoute
  '/members': typeof AuthenticatedAdminMembersRoute
  '/class-detail/$id': typeof AuthenticatedAdminClassDetailIdRoute
  '/member-detail/$id': typeof AuthenticatedAdminMemberDetailIdRoute
  '/member-profile/$id': typeof AuthenticatedAdminMemberProfileIdRoute
  '/more/coaches': typeof AuthenticatedAdminMoreCoachesRoute
  '/more/files': typeof AuthenticatedAdminMoreFilesRoute
  '/more/invites': typeof AuthenticatedAdminMoreInvitesRoute
  '/more/my-profile': typeof AuthenticatedAdminMoreMyProfileRoute
  '/more/notifications': typeof AuthenticatedAdminMoreNotificationsRoute
  '/more/plans': typeof AuthenticatedAdminMorePlansRoute
  '/more/reports': typeof AuthenticatedAdminMoreReportsRoute
  '/more/settings': typeof AuthenticatedAdminMoreSettingsRoute
  '/more/wod': typeof AuthenticatedAdminMoreWodRoute
  '/more/': typeof AuthenticatedAdminMoreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/classes': typeof AuthenticatedAdminClassesRoute
  '/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/finances': typeof AuthenticatedAdminFinancesRoute
  '/members': typeof AuthenticatedAdminMembersRoute
  '/class-detail/$id': typeof AuthenticatedAdminClassDetailIdRoute
  '/member-detail/$id': typeof AuthenticatedAdminMemberDetailIdRoute
  '/member-profile/$id': typeof AuthenticatedAdminMemberProfileIdRoute
  '/more/coaches': typeof AuthenticatedAdminMoreCoachesRoute
  '/more/files': typeof AuthenticatedAdminMoreFilesRoute
  '/more/invites': typeof AuthenticatedAdminMoreInvitesRoute
  '/more/my-profile': typeof AuthenticatedAdminMoreMyProfileRoute
  '/more/notifications': typeof AuthenticatedAdminMoreNotificationsRoute
  '/more/plans': typeof AuthenticatedAdminMorePlansRoute
  '/more/reports': typeof AuthenticatedAdminMoreReportsRoute
  '/more/settings': typeof AuthenticatedAdminMoreSettingsRoute
  '/more/wod': typeof AuthenticatedAdminMoreWodRoute
  '/more': typeof AuthenticatedAdminMoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/_admin/classes': typeof AuthenticatedAdminClassesRoute
  '/_authenticated/_admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/_admin/finances': typeof AuthenticatedAdminFinancesRoute
  '/_authenticated/_admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/_admin/class-detail/$id': typeof AuthenticatedAdminClassDetailIdRoute
  '/_authenticated/_admin/member-detail/$id': typeof AuthenticatedAdminMemberDetailIdRoute
  '/_authenticated/_admin/member-profile/$id': typeof AuthenticatedAdminMemberProfileIdRoute
  '/_authenticated/_admin/more/coaches': typeof AuthenticatedAdminMoreCoachesRoute
  '/_authenticated/_admin/more/files': typeof AuthenticatedAdminMoreFilesRoute
  '/_authenticated/_admin/more/invites': typeof AuthenticatedAdminMoreInvitesRoute
  '/_authenticated/_admin/more/my-profile': typeof AuthenticatedAdminMoreMyProfileRoute
  '/_authenticated/_admin/more/notifications': typeof AuthenticatedAdminMoreNotificationsRoute
  '/_authenticated/_admin/more/plans': typeof AuthenticatedAdminMorePlansRoute
  '/_authenticated/_admin/more/reports': typeof AuthenticatedAdminMoreReportsRoute
  '/_authenticated/_admin/more/settings': typeof AuthenticatedAdminMoreSettingsRoute
  '/_authenticated/_admin/more/wod': typeof AuthenticatedAdminMoreWodRoute
  '/_authenticated/_admin/more/': typeof AuthenticatedAdminMoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/classes'
    | '/dashboard'
    | '/finances'
    | '/members'
    | '/class-detail/$id'
    | '/member-detail/$id'
    | '/member-profile/$id'
    | '/more/coaches'
    | '/more/files'
    | '/more/invites'
    | '/more/my-profile'
    | '/more/notifications'
    | '/more/plans'
    | '/more/reports'
    | '/more/settings'
    | '/more/wod'
    | '/more/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/classes'
    | '/dashboard'
    | '/finances'
    | '/members'
    | '/class-detail/$id'
    | '/member-detail/$id'
    | '/member-profile/$id'
    | '/more/coaches'
    | '/more/files'
    | '/more/invites'
    | '/more/my-profile'
    | '/more/notifications'
    | '/more/plans'
    | '/more/reports'
    | '/more/settings'
    | '/more/wod'
    | '/more'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/_admin'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/_admin/classes'
    | '/_authenticated/_admin/dashboard'
    | '/_authenticated/_admin/finances'
    | '/_authenticated/_admin/members'
    | '/_authenticated/_admin/class-detail/$id'
    | '/_authenticated/_admin/member-detail/$id'
    | '/_authenticated/_admin/member-profile/$id'
    | '/_authenticated/_admin/more/coaches'
    | '/_authenticated/_admin/more/files'
    | '/_authenticated/_admin/more/invites'
    | '/_authenticated/_admin/more/my-profile'
    | '/_authenticated/_admin/more/notifications'
    | '/_authenticated/_admin/more/plans'
    | '/_authenticated/_admin/more/reports'
    | '/_authenticated/_admin/more/settings'
    | '/_authenticated/_admin/more/wod'
    | '/_authenticated/_admin/more/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/classes': {
      id: '/_authenticated/_admin/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedAdminClassesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/dashboard': {
      id: '/_authenticated/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/finances': {
      id: '/_authenticated/_admin/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedAdminFinancesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/members': {
      id: '/_authenticated/_admin/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/class-detail/$id': {
      id: '/_authenticated/_admin/class-detail/$id'
      path: '/class-detail/$id'
      fullPath: '/class-detail/$id'
      preLoaderRoute: typeof AuthenticatedAdminClassDetailIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/member-detail/$id': {
      id: '/_authenticated/_admin/member-detail/$id'
      path: '/member-detail/$id'
      fullPath: '/member-detail/$id'
      preLoaderRoute: typeof AuthenticatedAdminMemberDetailIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/member-profile/$id': {
      id: '/_authenticated/_admin/member-profile/$id'
      path: '/member-profile/$id'
      fullPath: '/member-profile/$id'
      preLoaderRoute: typeof AuthenticatedAdminMemberProfileIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/more/': {
      id: '/_authenticated/_admin/more/'
      path: '/more'
      fullPath: '/more/'
      preLoaderRoute: typeof AuthenticatedAdminMoreIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/more/coaches': {
      id: '/_authenticated/_admin/more/coaches'
      path: '/more/coaches'
      fullPath: '/more/coaches'
      preLoaderRoute: typeof AuthenticatedAdminMoreCoachesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/more/files': {
      id: '/_authenticated/_admin/more/files'
      path: '/more/files'
      fullPath: '/more/files'
      preLoaderRoute: typeof AuthenticatedAdminMoreFilesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/more/invites': {
      id: '/_authenticated/_admin/more/invites'
      path: '/more/invites'
      fullPath: '/more/invites'
      preLoaderRoute: typeof AuthenticatedAdminMoreInvitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/more/my-profile': {
      id: '/_authenticated/_admin/more/my-profile'
      path: '/more/my-profile'
      fullPath: '/more/my-profile'
      preLoaderRoute: typeof AuthenticatedAdminMoreMyProfileRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/more/notifications': {
      id: '/_authenticated/_admin/more/notifications'
      path: '/more/notifications'
      fullPath: '/more/notifications'
      preLoaderRoute: typeof AuthenticatedAdminMoreNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/more/plans': {
      id: '/_authenticated/_admin/more/plans'
      path: '/more/plans'
      fullPath: '/more/plans'
      preLoaderRoute: typeof AuthenticatedAdminMorePlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/more/reports': {
      id: '/_authenticated/_admin/more/reports'
      path: '/more/reports'
      fullPath: '/more/reports'
      preLoaderRoute: typeof AuthenticatedAdminMoreReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/more/settings': {
      id: '/_authenticated/_admin/more/settings'
      path: '/more/settings'
      fullPath: '/more/settings'
      preLoaderRoute: typeof AuthenticatedAdminMoreSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/more/wod': {
      id: '/_authenticated/_admin/more/wod'
      path: '/more/wod'
      fullPath: '/more/wod'
      preLoaderRoute: typeof AuthenticatedAdminMoreWodRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClassesRoute: typeof AuthenticatedAdminClassesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminFinancesRoute: typeof AuthenticatedAdminFinancesRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminClassDetailIdRoute: typeof AuthenticatedAdminClassDetailIdRoute
  AuthenticatedAdminMemberDetailIdRoute: typeof AuthenticatedAdminMemberDetailIdRoute
  AuthenticatedAdminMemberProfileIdRoute: typeof AuthenticatedAdminMemberProfileIdRoute
  AuthenticatedAdminMoreCoachesRoute: typeof AuthenticatedAdminMoreCoachesRoute
  AuthenticatedAdminMoreFilesRoute: typeof AuthenticatedAdminMoreFilesRoute
  AuthenticatedAdminMoreInvitesRoute: typeof AuthenticatedAdminMoreInvitesRoute
  AuthenticatedAdminMoreMyProfileRoute: typeof AuthenticatedAdminMoreMyProfileRoute
  AuthenticatedAdminMoreNotificationsRoute: typeof AuthenticatedAdminMoreNotificationsRoute
  AuthenticatedAdminMorePlansRoute: typeof AuthenticatedAdminMorePlansRoute
  AuthenticatedAdminMoreReportsRoute: typeof AuthenticatedAdminMoreReportsRoute
  AuthenticatedAdminMoreSettingsRoute: typeof AuthenticatedAdminMoreSettingsRoute
  AuthenticatedAdminMoreWodRoute: typeof AuthenticatedAdminMoreWodRoute
  AuthenticatedAdminMoreIndexRoute: typeof AuthenticatedAdminMoreIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClassesRoute: AuthenticatedAdminClassesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminFinancesRoute: AuthenticatedAdminFinancesRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminClassDetailIdRoute: AuthenticatedAdminClassDetailIdRoute,
  AuthenticatedAdminMemberDetailIdRoute: AuthenticatedAdminMemberDetailIdRoute,
  AuthenticatedAdminMemberProfileIdRoute:
    AuthenticatedAdminMemberProfileIdRoute,
  AuthenticatedAdminMoreCoachesRoute: AuthenticatedAdminMoreCoachesRoute,
  AuthenticatedAdminMoreFilesRoute: AuthenticatedAdminMoreFilesRoute,
  AuthenticatedAdminMoreInvitesRoute: AuthenticatedAdminMoreInvitesRoute,
  AuthenticatedAdminMoreMyProfileRoute: AuthenticatedAdminMoreMyProfileRoute,
  AuthenticatedAdminMoreNotificationsRoute:
    AuthenticatedAdminMoreNotificationsRoute,
  AuthenticatedAdminMorePlansRoute: AuthenticatedAdminMorePlansRoute,
  AuthenticatedAdminMoreReportsRoute: AuthenticatedAdminMoreReportsRoute,
  AuthenticatedAdminMoreSettingsRoute: AuthenticatedAdminMoreSettingsRoute,
  AuthenticatedAdminMoreWodRoute: AuthenticatedAdminMoreWodRoute,
  AuthenticatedAdminMoreIndexRoute: AuthenticatedAdminMoreIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
