/**
 * Account recovery for wodplace athletes — hand-written (not generated by
 * orval), same infrastructure as social.ts / users.ts.
 *
 * wodplace has no real server auth: the account id lives only in the
 * phone's AsyncStorage. If it's lost (reinstall / cleared data), these
 * two calls let the athlete prove ownership of the email on file and get
 * the existing id back so the phone can re-adopt it.
 */
import { customFetch } from "./custom-fetch";

/** Always resolves the same way regardless of whether the email exists. */
export async function requestAccountRecovery(email: string): Promise<void> {
  await customFetch("/api/account-recovery/request", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ email }),
  });
}

export type RecoveredAccount = {
  userId: string;
  name: string;
  email: string;
  avatarUrl: string | null;
  rank: string | null;
  phrase: string | null;
};

/**
 * Throws with a human message on a wrong/expired code or a lockout. On
 * success returns the account's server-side profile.
 */
export async function verifyAccountRecovery(
  email: string,
  code: string,
): Promise<RecoveredAccount> {
  return customFetch<RecoveredAccount>("/api/account-recovery/verify", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ email, code }),
  });
}
