/**
 * Hand-written (not generated by orval), same infrastructure as myBox.ts /
 * platformAgreement.ts / accountRecovery.ts.
 */
import { customFetch } from "./custom-fetch";

export type AchievementView = {
  id: string;
  name: string;
  description: string;
  icon: string;
  unlocked: boolean;
  unlockedAt: string | null;
};

export type AchievementCategory = {
  id: string;
  name: string;
  unlocked: number;
  total: number;
  achievements: AchievementView[];
};

export type FeaturedPr = {
  movementId: string;
  liftName: string;
  weightKg: number;
  improvementPct: number;
};

export type AchievementsResult = {
  categories: AchievementCategory[];
  stats: {
    totalBookings: number;
    currentStreakDays: number;
    featuredPr: FeaturedPr | null;
    phrase: string | null;
  };
};

export async function getAchievements(userId: string): Promise<AchievementsResult> {
  return customFetch<AchievementsResult>(
    `/api/achievements?userId=${encodeURIComponent(userId)}`,
  );
}
