/**
 * The box an already-enrolled athlete belongs to — real data behind what
 * wodplace's box-detail.tsx used to render from the hardcoded
 * constants/boxInfo.ts mock. Hand-written (not generated by orval), same
 * infrastructure as platformAgreement.ts / accountRecovery.ts.
 */
import { customFetch } from "./custom-fetch";

export type MyBox = {
  name: string;
  ownerName: string | null;
  location: string | null;
  contactPhone: string | null;
  whatsapp: string | null;
  instagramUrl: string | null;
  facebookUrl: string | null;
  tiktokUrl: string | null;
};

export async function getMyBox(userId: string): Promise<{ box: MyBox | null }> {
  return customFetch<{ box: MyBox | null }>(
    `/api/box-memberships/my-box?userId=${encodeURIComponent(userId)}`,
  );
}
