/**
 * The box an already-enrolled athlete belongs to — real data behind what
 * wodplace's box-detail.tsx used to render from the hardcoded
 * constants/boxInfo.ts mock. Hand-written (not generated by orval), same
 * infrastructure as platformAgreement.ts.
 */
import { useCallback, useEffect, useState } from "react";
import { customFetch } from "./custom-fetch";

export type MyBox = {
  name: string;
  ownerName: string | null;
  location: string | null;
  contactPhone: string | null;
  whatsapp: string | null;
  instagramUrl: string | null;
  facebookUrl: string | null;
  tiktokUrl: string | null;
  /** The box's "logo" — really just its profile photo, same concept as an
   *  athlete's avatar. Set from box-admin's own "Configuración". */
  photoUrl: string | null;
  /** null until the box_admin assigns one — drives whether "Progreso
   *  Mensual" shows on Home (belonging to a box isn't the same as having
   *  an assigned plan). */
  planId: string | null;
};

export async function getMyBox(userId: string): Promise<{ box: MyBox | null }> {
  return customFetch<{ box: MyBox | null }>(
    `/api/box-memberships/my-box?userId=${encodeURIComponent(userId)}`,
  );
}

export type UpcomingBirthday = {
  name: string;
  /** 1-12. Never the year — see wodplace_users.birthdate's own doc comment. */
  month: number;
  /** 1-31. */
  day: number;
  daysUntil: number;
};

export async function getUpcomingBirthdays(
  userId: string,
  limit = 5,
): Promise<{ birthdays: UpcomingBirthday[] }> {
  return customFetch<{ birthdays: UpcomingBirthday[] }>(
    `/api/box-memberships/upcoming-birthdays?userId=${encodeURIComponent(userId)}&limit=${limit}`,
  );
}

export type MyPlan = {
  id: string;
  name: string;
  price: number;
  durationDays: number;
  /** null means unlimited (no fixed class count). */
  classesPerPeriod: number | null;
  benefits: string[];
  isFeatured: boolean;
  isSubscribed: boolean;
  /** Only ever set on the subscribed plan — null on every other plan, and
   *  null on the subscribed one too until a payment (or first assignment)
   *  seeds box_members.next_payment_at. */
  daysUntilRenewal: number | null;
  classesUsedInPeriod: number | null;
  classesRemaining: number | null;
};

export async function getMyPlans(userId: string): Promise<{ plans: MyPlan[] }> {
  return customFetch<{ plans: MyPlan[] }>(
    `/api/box-memberships/my-plans?userId=${encodeURIComponent(userId)}`,
  );
}

/** A box-admin "Aviso" (announcements table), as shown to the athlete. */
export type BoxAnnouncement = {
  id: string;
  title: string;
  body: string;
  imageUrl: string | null;
  createdAt: string;
  readByMe: boolean;
  /** Likes — announcement_reactions, kept separate from social_reactions
   *  (avisos and community posts are different models; see that table's
   *  own doc comment in lib/db). */
  reactions: { emoji: string; count: number }[];
  myReaction: string | null;
  commentCount: number;
};

export type BoxAnnouncements = {
  /** Unread, send_push=true — Home's must-acknowledge popup queue, most
   *  recent first. Drops off this list once confirmed read. */
  push: BoxAnnouncement[];
  /** The single most recent send_push=true aviso, regardless of read state
   *  — Home's persistent "Progreso Mensual" card below section, so it's
   *  still findable after the popup's been confirmed (which removes it
   *  from `push`, but not from here). */
  pinnedPush: BoxAnnouncement | null;
  /** show_banner=true, regardless of read state — mixed into Comunidad's
   *  feed as a regular-looking post. */
  banner: BoxAnnouncement[];
};

export async function getBoxAnnouncements(userId: string): Promise<BoxAnnouncements> {
  return customFetch<BoxAnnouncements>(
    `/api/box-memberships/announcements?userId=${encodeURIComponent(userId)}`,
  );
}

export async function markAnnouncementRead(id: string, userId: string): Promise<void> {
  await customFetch(`/api/box-memberships/announcements/${encodeURIComponent(id)}/read`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ userId }),
  });
}

// ─── Aviso comments/reactions ───────────────────────────────────────────────
// Mirrors social.ts's useComments/useSocialMutations shape, pointed at the
// announcement_comments/announcement_reactions endpoints instead.

export type AnnouncementComment = {
  id: string;
  announcementId: string;
  userId: string | null;
  authorName: string;
  body: string;
  createdAt: string;
};

export function useAnnouncementComments(announcementId: string | null) {
  const [comments, setComments] = useState<AnnouncementComment[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [nextCursor, setNextCursor] = useState<string | null>(null);
  const [hasMore, setHasMore] = useState(false);

  const load = useCallback(
    async (cursor?: string) => {
      if (!announcementId) return;
      if (!cursor) setIsLoading(true);
      try {
        const p = new URLSearchParams({ limit: "20", ...(cursor ? { cursor } : {}) });
        const data = await customFetch<{
          comments: AnnouncementComment[];
          nextCursor: string | null;
          hasMore: boolean;
        }>(`/api/box-memberships/announcements/${announcementId}/comments?${p}`);
        setComments((prev) => (cursor ? [...prev, ...data.comments] : data.comments));
        setNextCursor(data.nextCursor);
        setHasMore(data.hasMore);
      } catch {
        if (!cursor) setComments([]);
      } finally {
        setIsLoading(false);
      }
    },
    [announcementId],
  );

  useEffect(() => {
    if (announcementId) { setComments([]); setNextCursor(null); load(undefined); }
    else setComments([]);
  }, [announcementId, load]);

  const refresh = useCallback(() => { setNextCursor(null); load(undefined); }, [load]);
  const fetchNextPage = useCallback(() => { if (hasMore && nextCursor) load(nextCursor); }, [hasMore, nextCursor, load]);

  return { comments, isLoading, hasMore, fetchNextPage, refresh };
}

export function useAnnouncementMutations(userId: string, authorName: string) {
  const toggleReaction = useCallback(
    (announcementId: string, emoji: string) =>
      customFetch<{ added: boolean; myReaction: string | null; reactions: BoxAnnouncement["reactions"] }>(
        `/api/box-memberships/announcements/${announcementId}/reactions`,
        { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId, emoji }) },
      ),
    [userId],
  );

  const addComment = useCallback(
    (announcementId: string, body: string): Promise<AnnouncementComment> =>
      customFetch<AnnouncementComment>(`/api/box-memberships/announcements/${announcementId}/comments`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ userId, authorName, body }),
      }),
    [userId, authorName],
  );

  const deleteComment = useCallback(
    async (announcementId: string, commentId: string, adminCode?: string): Promise<void> => {
      const headers: Record<string, string> = {};
      if (adminCode) headers.Authorization = `Bearer ${adminCode}`;
      await customFetch(
        `/api/box-memberships/announcements/${announcementId}/comments/${commentId}?userId=${encodeURIComponent(userId)}`,
        { method: "DELETE", headers },
      );
    },
    [userId],
  );

  return { toggleReaction, addComment, deleteComment };
}
