/**
 * Platform agreement — between WODPLACE (super_admin) and each box's
 * box_admin, about using the software. Hand-written (not generated by
 * orval), same infrastructure as accountRecovery.ts / social.ts. Drives
 * whether the app's "Administrador" nav item shows up at all, and if so
 * whether it opens the admin panel directly or an acceptance screen first.
 */
import { customFetch } from "./custom-fetch";

export type AdminRole = "box_admin" | "super_admin";

export type PlatformAgreementStatus = {
  /** Every admin role this account holds — empty means "not an admin at
   *  all". An account can hold both (e.g. the platform owner, who is also
   *  her own box's box_admin). */
  roles: AdminRole[];
  accepted: boolean;
  document: { slug: string; title: string; objectPath: string | null } | null;
};

export async function getPlatformAgreementStatus(
  userId: string,
): Promise<PlatformAgreementStatus> {
  return customFetch<PlatformAgreementStatus>(
    `/api/platform-agreement?userId=${encodeURIComponent(userId)}`,
  );
}

export async function acceptPlatformAgreement(
  userId: string,
): Promise<PlatformAgreementStatus> {
  return customFetch<PlatformAgreementStatus>("/api/platform-agreement/accept", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ userId }),
  });
}
