/**
 * Social feed hooks — hand-written (not generated by orval).
 * Uses the same customFetch infrastructure so the base URL and auth
 * token are applied automatically.
 */
import { useCallback, useEffect, useRef, useState } from "react";
import { customFetch } from "./custom-fetch";
import { putImageToPresignedUrl, type NativeUploader } from "./imageUpload";

// ─── Types ────────────────────────────────────────────────────────────────────

export type SocialPost = {
  id: string;
  userId: string | null;
  authorName: string;
  body: string;
  imageUris: string[];
  type: string;
  createdAt: string;
  canEdit: boolean;
  reactions: { emoji: string; count: number }[];
  myReaction: string | null;
  commentCount: number;
};

export type SocialComment = {
  id: string;
  postId: string;
  userId: string | null;
  authorName: string;
  body: string;
  createdAt: string;
};

export type SocialReport = {
  id: string;
  postId: string;
  reporterName: string;
  reason: string;
  createdAt: string;
  post: {
    id: string;
    authorName: string;
    body: string;
    createdAt: string;
    deletedAt: string | null;
  } | null;
};

type FeedPage = { posts: SocialPost[]; nextCursor: string | null; hasMore: boolean };

// ─── Box name ─────────────────────────────────────────────────────────────────
//
// NOTE: the `adminCode` / `code` params below now carry the admin *session
// token* from the PIN flow (sent as `Authorization: Bearer <token>`), not the
// old shared access code. The names are kept to avoid churn at the call sites.

export function useBoxName() {
  const [name, setName] = useState("");
  useEffect(() => {
    customFetch<{ name: string }>("/api/settings/box-name")
      .then((d) => setName(d.name))
      .catch(() => {});
  }, []);
  return { name };
}

export function useAdminBoxName(adminCode: string | null) {
  const [name, setName] = useState("");

  useEffect(() => {
    customFetch<{ name: string }>("/api/settings/box-name")
      .then((d) => setName(d.name))
      .catch(() => {});
  }, []);

  const save = useCallback(
    async (newName: string) => {
      if (!adminCode) return;
      const data = await customFetch<{ name: string }>("/api/admin/settings/box-name", {
        method: "PUT",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${adminCode}` },
        body: JSON.stringify({ name: newName }),
      });
      setName(data.name);
    },
    [adminCode],
  );

  return { name, setName, save };
}

// ─── Paginated feed helper ────────────────────────────────────────────────────

function usePaginatedFeed(
  buildUrl: (cursor?: string) => string,
  trigger: unknown,
) {
  const [posts, setPosts] = useState<SocialPost[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isFetchingNextPage, setIsFetchingNextPage] = useState(false);
  const [nextCursor, setNextCursor] = useState<string | null>(null);
  const [hasMore, setHasMore] = useState(true);
  const buildUrlRef = useRef(buildUrl);
  buildUrlRef.current = buildUrl;

  const load = useCallback(async (cursor?: string) => {
    if (cursor) setIsFetchingNextPage(true);
    else setIsLoading(true);
    try {
      const data = await customFetch<FeedPage>(buildUrlRef.current(cursor));
      setPosts((prev: SocialPost[]) => (cursor ? [...prev, ...data.posts] : data.posts));
      setNextCursor(data.nextCursor);
      setHasMore(data.hasMore);
    } catch {
      if (!cursor) setPosts([]);
    } finally {
      setIsLoading(false);
      setIsFetchingNextPage(false);
    }
  }, []);

  // Re-trigger initial load when `trigger` changes (e.g. userId).
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { load(undefined); }, [trigger]);

  const refresh = useCallback(() => {
    setNextCursor(null);
    setHasMore(true);
    load(undefined);
  }, [load]);

  const fetchNextPage = useCallback(() => {
    if (!isFetchingNextPage && hasMore && nextCursor) load(nextCursor);
  }, [isFetchingNextPage, hasMore, nextCursor, load]);

  const updatePost = useCallback((postId: string, updates: Partial<SocialPost>) => {
    setPosts((prev: SocialPost[]) => prev.map((p: SocialPost) => (p.id === postId ? { ...p, ...updates } : p)));
  }, []);

  const removePost = useCallback((postId: string) => {
    setPosts((prev: SocialPost[]) => prev.filter((p: SocialPost) => p.id !== postId));
  }, []);

  const prependPost = useCallback((post: SocialPost) => {
    setPosts((prev: SocialPost[]) => [post, ...prev]);
  }, []);

  return {
    posts, isLoading, isFetchingNextPage, hasMore,
    fetchNextPage, refresh, updatePost, removePost, prependPost,
  };
}

// ─── Social feed ─────────────────────────────────────────────────────────────

export function useSocialFeed(userId?: string) {
  return usePaginatedFeed((cursor) => {
    const p = new URLSearchParams({ limit: "15", ...(userId ? { userId } : {}), ...(cursor ? { cursor } : {}) });
    return `/api/social/feed?${p}`;
  }, userId);
}

// ─── My posts ─────────────────────────────────────────────────────────────────

/**
 * Posts authored by `userId`. `viewerId` defaults to `userId` (the original
 * "my own posts" use case) — pass the actual signed-in user's id when
 * showing someone else's posts (e.g. the public member profile) so
 * canEdit/myReaction are computed for the real viewer, not the profile
 * owner.
 */
export function useMyPosts(userId: string, viewerId?: string) {
  return usePaginatedFeed((cursor) => {
    const p = new URLSearchParams({
      userId,
      viewerId: viewerId ?? userId,
      limit: "15",
      ...(cursor ? { cursor } : {}),
    });
    return `/api/social/posts/mine?${p}`;
  }, `${userId}:${viewerId ?? userId}`);
}

// ─── Comments ─────────────────────────────────────────────────────────────────

export function useComments(postId: string | null) {
  const [comments, setComments] = useState<SocialComment[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [nextCursor, setNextCursor] = useState<string | null>(null);
  const [hasMore, setHasMore] = useState(false);

  const load = useCallback(
    async (cursor?: string) => {
      if (!postId) return;
      if (!cursor) setIsLoading(true);
      try {
        const p = new URLSearchParams({ limit: "20", ...(cursor ? { cursor } : {}) });
        const data = await customFetch<{
          comments: SocialComment[];
          nextCursor: string | null;
          hasMore: boolean;
        }>(`/api/social/posts/${postId}/comments?${p}`);
        setComments((prev: SocialComment[]) => (cursor ? [...prev, ...data.comments] : data.comments));
        setNextCursor(data.nextCursor);
        setHasMore(data.hasMore);
      } catch {
        if (!cursor) setComments([]);
      } finally {
        setIsLoading(false);
      }
    },
    [postId],
  );

  useEffect(() => {
    if (postId) { setComments([]); setNextCursor(null); load(undefined); }
    else setComments([]);
  }, [postId, load]);

  const refresh = useCallback(() => { setNextCursor(null); load(undefined); }, [load]);
  const fetchNextPage = useCallback(() => { if (hasMore && nextCursor) load(nextCursor); }, [hasMore, nextCursor, load]);

  return { comments, isLoading, hasMore, fetchNextPage, refresh };
}

// ─── Mutations ────────────────────────────────────────────────────────────────

export function useSocialMutations(userId: string, authorName: string) {
  const createPost = useCallback(
    (body: string, imageUris: string[], type = "post"): Promise<SocialPost> =>
      customFetch<SocialPost>("/api/social/posts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ userId, authorName, body, imageUris, type }),
      }),
    [userId, authorName],
  );

  const editPost = useCallback(
    (postId: string, body: string): Promise<SocialPost> =>
      customFetch<SocialPost>(`/api/social/posts/${postId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ userId, body }),
      }),
    [userId],
  );

  const deletePost = useCallback(
    async (postId: string, adminCode?: string): Promise<void> => {
      const headers: Record<string, string> = {};
      if (adminCode) headers.Authorization = `Bearer ${adminCode}`;
      await customFetch(
        `/api/social/posts/${postId}?userId=${encodeURIComponent(userId)}`,
        { method: "DELETE", headers },
      );
    },
    [userId],
  );

  const toggleReaction = useCallback(
    (postId: string, emoji: string) =>
      customFetch<{ added: boolean; myReaction: string | null; reactions: SocialPost["reactions"] }>(
        `/api/social/posts/${postId}/reactions`,
        { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId, emoji }) },
      ),
    [userId],
  );

  const addComment = useCallback(
    (postId: string, body: string): Promise<SocialComment> =>
      customFetch<SocialComment>(`/api/social/posts/${postId}/comments`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ userId, authorName, body }),
      }),
    [userId, authorName],
  );

  const deleteComment = useCallback(
    async (postId: string, commentId: string, adminCode?: string): Promise<void> => {
      const headers: Record<string, string> = {};
      if (adminCode) headers.Authorization = `Bearer ${adminCode}`;
      await customFetch(
        `/api/social/posts/${postId}/comments/${commentId}?userId=${encodeURIComponent(userId)}`,
        { method: "DELETE", headers },
      );
    },
    [userId],
  );

  const reportPost = useCallback(
    async (postId: string, reason: string): Promise<void> => {
      await customFetch(`/api/social/posts/${postId}/report`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ reporterId: userId, reporterName: authorName, reason }),
      });
    },
    [userId, authorName],
  );

  const uploadSocialImage = useCallback(
    async (
      localUri: string,
      mimeType = "image/jpeg",
      nativeUploader?: NativeUploader,
      /**
       * Actual file size in bytes, when the caller knows it (e.g. from
       * ImagePicker's `fileSize`). Purely informational — omitted from the
       * request when unknown; the server tolerates a missing size.
       */
      fileSize?: number,
    ): Promise<string> => {
      // Step 1: request a presigned Supabase Storage upload URL from our API
      const { uploadURL, publicUrl } = await customFetch<{
        uploadURL: string;
        publicUrl: string;
        metadata: object;
      }>("/api/storage/social-uploads/request-url", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          userId,
          name: "photo.jpg",
          // Only send a size we actually know; JSON.stringify drops undefined.
          size: fileSize && fileSize > 0 ? fileSize : undefined,
          contentType: mimeType,
        }),
      });

      // Step 2: PUT the file bytes to the presigned upload URL.
      await putImageToPresignedUrl(uploadURL, localUri, mimeType, nativeUploader);

      return publicUrl;
    },
    [userId],
  );

  const blockUser = useCallback(
    async (targetUserId: string, adminCode: string): Promise<void> => {
      await customFetch(`/api/admin/users/${targetUserId}/block`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${adminCode}` },
        body: JSON.stringify({}),
      });
    },
    [],
  );

  return { createPost, editPost, deletePost, toggleReaction, addComment, deleteComment, reportPost, uploadSocialImage, blockUser };
}

// ─── Admin: reports queue ─────────────────────────────────────────────────────

export function useAdminSocialReports(adminCode: string | null) {
  const [reports, setReports] = useState<SocialReport[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const fetchReports = useCallback(async () => {
    if (!adminCode) return;
    setIsLoading(true);
    try {
      const data = await customFetch<SocialReport[]>("/api/admin/social/reports", {
        headers: { Authorization: `Bearer ${adminCode}` },
      });
      setReports(data);
    } catch {
      setReports([]);
    } finally {
      setIsLoading(false);
    }
  }, [adminCode]);

  useEffect(() => { fetchReports(); }, [fetchReports]);

  const resolve = useCallback(
    async (reportId: string, deletePost: boolean, overrideCode?: string) => {
      const code = overrideCode ?? adminCode;
      if (!code) return;
      if (deletePost) {
        const report = (await customFetch<SocialReport[]>("/api/admin/social/reports", {
          headers: { Authorization: `Bearer ${code}` },
        }).catch(() => [] as SocialReport[])).find((r: SocialReport) => r.id === reportId);
        if (report?.postId) {
          await customFetch(`/api/social/posts/${report.postId}`, {
            method: "DELETE",
            headers: { "Content-Type": "application/json", Authorization: `Bearer ${code}` },
            body: JSON.stringify({ userId: "admin" }),
          }).catch(() => {});
        }
      }
      await customFetch(`/api/admin/social/reports/${reportId}/resolve`, {
        method: "PATCH",
        headers: { Authorization: `Bearer ${code}` },
      });
      setReports((prev: SocialReport[]) => prev.filter((r: SocialReport) => r.id !== reportId));
    },
    [adminCode],
  );

  return { reports, isLoading, refresh: fetchReports, resolve };
}
