/**
 * Social feed hooks — hand-written (not generated by orval).
 * Uses the same customFetch infrastructure so the base URL and auth
 * token are applied automatically.
 */
import { useCallback, useEffect, useRef, useState } from "react";
import { Platform } from "react-native";
import { customFetch, getApiBaseUrl } from "./custom-fetch";

// ─── Types ────────────────────────────────────────────────────────────────────

export type SocialPost = {
  id: string;
  userId: string | null;
  authorName: string;
  body: string;
  imageUris: string[];
  type: string;
  createdAt: string;
  canEdit: boolean;
  reactions: { emoji: string; count: number }[];
  myReaction: string | null;
  commentCount: number;
};

export type SocialComment = {
  id: string;
  postId: string;
  userId: string | null;
  authorName: string;
  body: string;
  createdAt: string;
};

export type SocialReport = {
  id: string;
  postId: string;
  reporterName: string;
  reason: string;
  createdAt: string;
  post: {
    id: string;
    authorName: string;
    body: string;
    createdAt: string;
    deletedAt: string | null;
  } | null;
};

type FeedPage = { posts: SocialPost[]; nextCursor: string | null; hasMore: boolean };

// ─── Box name ─────────────────────────────────────────────────────────────────

export function useBoxName() {
  const [name, setName] = useState("");
  useEffect(() => {
    customFetch<{ name: string }>("/api/settings/box-name")
      .then((d) => setName(d.name))
      .catch(() => {});
  }, []);
  return { name };
}

export function useAdminBoxName(adminCode: string | null) {
  const [name, setName] = useState("");

  useEffect(() => {
    customFetch<{ name: string }>("/api/settings/box-name")
      .then((d) => setName(d.name))
      .catch(() => {});
  }, []);

  const save = useCallback(
    async (newName: string) => {
      if (!adminCode) return;
      const data = await customFetch<{ name: string }>("/api/admin/settings/box-name", {
        method: "PUT",
        headers: { "Content-Type": "application/json", "x-admin-code": adminCode },
        body: JSON.stringify({ name: newName }),
      });
      setName(data.name);
    },
    [adminCode],
  );

  return { name, setName, save };
}

// ─── Paginated feed helper ────────────────────────────────────────────────────

function usePaginatedFeed(
  buildUrl: (cursor?: string) => string,
  trigger: unknown,
) {
  const [posts, setPosts] = useState<SocialPost[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isFetchingNextPage, setIsFetchingNextPage] = useState(false);
  const [nextCursor, setNextCursor] = useState<string | null>(null);
  const [hasMore, setHasMore] = useState(true);
  const buildUrlRef = useRef(buildUrl);
  buildUrlRef.current = buildUrl;

  const load = useCallback(async (cursor?: string) => {
    if (cursor) setIsFetchingNextPage(true);
    else setIsLoading(true);
    try {
      const data = await customFetch<FeedPage>(buildUrlRef.current(cursor));
      setPosts((prev: SocialPost[]) => (cursor ? [...prev, ...data.posts] : data.posts));
      setNextCursor(data.nextCursor);
      setHasMore(data.hasMore);
    } catch {
      if (!cursor) setPosts([]);
    } finally {
      setIsLoading(false);
      setIsFetchingNextPage(false);
    }
  }, []);

  // Re-trigger initial load when `trigger` changes (e.g. userId).
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { load(undefined); }, [trigger]);

  const refresh = useCallback(() => {
    setNextCursor(null);
    setHasMore(true);
    load(undefined);
  }, [load]);

  const fetchNextPage = useCallback(() => {
    if (!isFetchingNextPage && hasMore && nextCursor) load(nextCursor);
  }, [isFetchingNextPage, hasMore, nextCursor, load]);

  const updatePost = useCallback((postId: string, updates: Partial<SocialPost>) => {
    setPosts((prev: SocialPost[]) => prev.map((p: SocialPost) => (p.id === postId ? { ...p, ...updates } : p)));
  }, []);

  const removePost = useCallback((postId: string) => {
    setPosts((prev: SocialPost[]) => prev.filter((p: SocialPost) => p.id !== postId));
  }, []);

  const prependPost = useCallback((post: SocialPost) => {
    setPosts((prev: SocialPost[]) => [post, ...prev]);
  }, []);

  return {
    posts, isLoading, isFetchingNextPage, hasMore,
    fetchNextPage, refresh, updatePost, removePost, prependPost,
  };
}

// ─── Social feed ─────────────────────────────────────────────────────────────

export function useSocialFeed(userId?: string) {
  return usePaginatedFeed((cursor) => {
    const p = new URLSearchParams({ limit: "15", ...(userId ? { userId } : {}), ...(cursor ? { cursor } : {}) });
    return `/api/social/feed?${p}`;
  }, userId);
}

// ─── My posts ─────────────────────────────────────────────────────────────────

export function useMyPosts(userId: string) {
  return usePaginatedFeed((cursor) => {
    const p = new URLSearchParams({ userId, limit: "15", ...(cursor ? { cursor } : {}) });
    return `/api/social/posts/mine?${p}`;
  }, userId);
}

// ─── Comments ─────────────────────────────────────────────────────────────────

export function useComments(postId: string | null) {
  const [comments, setComments] = useState<SocialComment[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [nextCursor, setNextCursor] = useState<string | null>(null);
  const [hasMore, setHasMore] = useState(false);

  const load = useCallback(
    async (cursor?: string) => {
      if (!postId) return;
      if (!cursor) setIsLoading(true);
      try {
        const p = new URLSearchParams({ limit: "20", ...(cursor ? { cursor } : {}) });
        const data = await customFetch<{
          comments: SocialComment[];
          nextCursor: string | null;
          hasMore: boolean;
        }>(`/api/social/posts/${postId}/comments?${p}`);
        setComments((prev: SocialComment[]) => (cursor ? [...prev, ...data.comments] : data.comments));
        setNextCursor(data.nextCursor);
        setHasMore(data.hasMore);
      } catch {
        if (!cursor) setComments([]);
      } finally {
        setIsLoading(false);
      }
    },
    [postId],
  );

  useEffect(() => {
    if (postId) { setComments([]); setNextCursor(null); load(undefined); }
    else setComments([]);
  }, [postId, load]);

  const refresh = useCallback(() => { setNextCursor(null); load(undefined); }, [load]);
  const fetchNextPage = useCallback(() => { if (hasMore && nextCursor) load(nextCursor); }, [hasMore, nextCursor, load]);

  return { comments, isLoading, hasMore, fetchNextPage, refresh };
}

// ─── Mutations ────────────────────────────────────────────────────────────────

export function useSocialMutations(userId: string, authorName: string) {
  const createPost = useCallback(
    (body: string, imageUris: string[], type = "post"): Promise<SocialPost> =>
      customFetch<SocialPost>("/api/social/posts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ userId, authorName, body, imageUris, type }),
      }),
    [userId, authorName],
  );

  const editPost = useCallback(
    (postId: string, body: string): Promise<SocialPost> =>
      customFetch<SocialPost>(`/api/social/posts/${postId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ userId, body }),
      }),
    [userId],
  );

  const deletePost = useCallback(
    async (postId: string, adminCode?: string): Promise<void> => {
      const headers: Record<string, string> = {};
      if (adminCode) headers["x-admin-code"] = adminCode;
      await customFetch(
        `/api/social/posts/${postId}?userId=${encodeURIComponent(userId)}`,
        { method: "DELETE", headers },
      );
    },
    [userId],
  );

  const toggleReaction = useCallback(
    (postId: string, emoji: string) =>
      customFetch<{ added: boolean; myReaction: string | null; reactions: SocialPost["reactions"] }>(
        `/api/social/posts/${postId}/reactions`,
        { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId, emoji }) },
      ),
    [userId],
  );

  const addComment = useCallback(
    (postId: string, body: string): Promise<SocialComment> =>
      customFetch<SocialComment>(`/api/social/posts/${postId}/comments`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ userId, authorName, body }),
      }),
    [userId, authorName],
  );

  const deleteComment = useCallback(
    async (postId: string, commentId: string, adminCode?: string): Promise<void> => {
      const headers: Record<string, string> = {};
      if (adminCode) headers["x-admin-code"] = adminCode;
      await customFetch(
        `/api/social/posts/${postId}/comments/${commentId}?userId=${encodeURIComponent(userId)}`,
        { method: "DELETE", headers },
      );
    },
    [userId],
  );

  const reportPost = useCallback(
    async (postId: string, reason: string): Promise<void> => {
      await customFetch(`/api/social/posts/${postId}/report`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ reporterId: userId, reporterName: authorName, reason }),
      });
    },
    [userId, authorName],
  );

  const uploadSocialImage = useCallback(
    async (localUri: string, mimeType = "image/jpeg"): Promise<string> => {
      // Step 1: request a presigned GCS upload URL from our API
      const { uploadURL, objectPath } = await customFetch<{
        uploadURL: string;
        objectPath: string;
        metadata: object;
      }>("/api/storage/social-uploads/request-url", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ userId, name: "photo.jpg", size: 0, contentType: mimeType }),
      });

      // Step 2: PUT the file to the presigned URL.
      // We use XMLHttpRequest instead of fetch because React Native's fetch()
      // does NOT support reading local file:// URIs.  XHR's send({ uri }) is
      // a React Native extension that reads the file from the filesystem.
      // On Expo web the localUri is a blob: URL which XHR also handles.
      const uploadStatus = await new Promise<number>((resolve, reject) => {
        const xhr = new XMLHttpRequest();
        xhr.open("PUT", uploadURL);
        xhr.setRequestHeader("Content-Type", mimeType);
        xhr.onreadystatechange = () => {
          if (xhr.readyState === 4) resolve(xhr.status);
        };
        xhr.onerror = () => reject(new Error("Network error during image upload"));
        xhr.ontimeout = () => reject(new Error("Image upload timed out"));

        if (Platform.OS === "web") {
          // On web, localUri is a blob: URL — fetch it into a Blob first
          fetch(localUri)
            .then((r) => r.blob())
            .then((blob) => xhr.send(blob))
            .catch(reject);
        } else {
          // React Native: XHR handles { uri } (file:// path) natively
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          xhr.send({ uri: localUri, type: mimeType, name: "photo.jpg" } as any);
        }
      });

      if (uploadStatus < 200 || uploadStatus >= 300) {
        throw new Error(`La imagen no se pudo subir (HTTP ${uploadStatus}). Intenta de nuevo.`);
      }

      const base = getApiBaseUrl();
      return `${base}/api/storage/objects/${objectPath.replace(/^\/objects\//, "")}`;
    },
    [userId],
  );

  const blockUser = useCallback(
    async (targetUserId: string, adminCode: string): Promise<void> => {
      await customFetch(`/api/admin/users/${targetUserId}/block`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "x-admin-code": adminCode },
        body: JSON.stringify({}),
      });
    },
    [],
  );

  return { createPost, editPost, deletePost, toggleReaction, addComment, deleteComment, reportPost, uploadSocialImage, blockUser };
}

// ─── Admin: reports queue ─────────────────────────────────────────────────────

export function useAdminSocialReports(adminCode: string | null) {
  const [reports, setReports] = useState<SocialReport[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const fetchReports = useCallback(async () => {
    if (!adminCode) return;
    setIsLoading(true);
    try {
      const data = await customFetch<SocialReport[]>("/api/admin/social/reports", {
        headers: { "x-admin-code": adminCode },
      });
      setReports(data);
    } catch {
      setReports([]);
    } finally {
      setIsLoading(false);
    }
  }, [adminCode]);

  useEffect(() => { fetchReports(); }, [fetchReports]);

  const resolve = useCallback(
    async (reportId: string, deletePost: boolean, overrideCode?: string) => {
      const code = overrideCode ?? adminCode;
      if (!code) return;
      if (deletePost) {
        const report = (await customFetch<SocialReport[]>("/api/admin/social/reports", {
          headers: { "x-admin-code": code },
        }).catch(() => [] as SocialReport[])).find((r: SocialReport) => r.id === reportId);
        if (report?.postId) {
          await customFetch(`/api/social/posts/${report.postId}`, {
            method: "DELETE",
            headers: { "Content-Type": "application/json", "x-admin-code": code },
            body: JSON.stringify({ userId: "admin" }),
          }).catch(() => {});
        }
      }
      await customFetch(`/api/admin/social/reports/${reportId}/resolve`, {
        method: "PATCH",
        headers: { "x-admin-code": code },
      });
      setReports((prev: SocialReport[]) => prev.filter((r: SocialReport) => r.id !== reportId));
    },
    [adminCode],
  );

  return { reports, isLoading, refresh: fetchReports, resolve };
}
