/**
 * User profile hooks — hand-written (not generated by orval), same
 * infrastructure as social.ts.
 */
import { useEffect, useState } from "react";
import { customFetch, getApiBaseUrl } from "./custom-fetch";
import { putImageToPresignedUrl, type NativeUploader } from "./imageUpload";

export type PublicProfile = {
  id: string;
  name: string;
  avatarUrl: string | null;
  /** ISO timestamp of the earliest box_members.joined_at across every box
   *  this user belongs to, or null if they don't belong to any. */
  memberSince: string | null;
};

/**
 * The athlete-facing profile shown from Comunidad — deliberately narrow
 * (identity + join date only). Never includes membership status, plan,
 * payments, or contracts; those stay admin-only in box-admin.
 */
export function usePublicProfile(userId: string | null) {
  const [profile, setProfile] = useState<PublicProfile | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    if (!userId) {
      setProfile(null);
      setIsLoading(false);
      return;
    }
    setIsLoading(true);
    customFetch<PublicProfile>(`/api/users/${userId}/public-profile`)
      .then(setProfile)
      .catch(() => setProfile(null))
      .finally(() => setIsLoading(false));
  }, [userId]);

  return { profile, isLoading };
}

/**
 * Uploads a new profile photo and records it as the athlete's avatar.
 * Mirrors useSocialMutations().uploadSocialImage — same presigned-URL flow,
 * a smaller dedicated endpoint (avatar-uploads vs social-uploads), and one
 * extra step to persist the resulting URL onto the user record so it shows
 * up everywhere that reads it (public profile, box-admin's member views).
 */
export async function uploadAvatarImage(
  userId: string,
  localUri: string,
  mimeType = "image/jpeg",
  nativeUploader?: NativeUploader,
  fileSize?: number,
): Promise<string> {
  const { uploadURL, objectPath } = await customFetch<{
    uploadURL: string;
    objectPath: string;
    metadata: object;
  }>("/api/storage/avatar-uploads/request-url", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      userId,
      size: fileSize && fileSize > 0 ? fileSize : undefined,
      contentType: mimeType,
    }),
  });

  await putImageToPresignedUrl(uploadURL, localUri, mimeType, nativeUploader);

  const base = getApiBaseUrl();
  const avatarUrl = `${base}/api/storage/objects/${objectPath.replace(/^\/objects\//, "")}`;

  await customFetch(`/api/users/${userId}/avatar`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ avatarUrl }),
  });

  return avatarUrl;
}
