/**
 * Hand-written (not generated by orval), same infrastructure as myBox.ts /
 * achievements.ts.
 */
import { customFetch } from "./custom-fetch";
import { SKILL_LEVELS, SKILL_LEVEL_LABELS, type SkillLevel } from "./skillLevel";

export type WodFormat = "for_time" | "amrap" | "max_reps";

/** Re-exported for existing call sites — see skillLevel.ts, the single
 *  source of truth shared with wodplace_users.rank. */
export const WOD_LEVELS = SKILL_LEVELS;
export const WOD_LEVEL_LABELS = SKILL_LEVEL_LABELS;
export type WodLevel = SkillLevel;

export type WodResultInput = {
  timeSeconds: number | null;
  rounds: number | null;
  reps: number | null;
  level: WodLevel;
  notes: string | null;
};

export type TodayWod = {
  wodOfDayId: string;
  wodId: string;
  name: string;
  format: WodFormat;
  timeCapMinutes: number | null;
  description: string;
  notes: string | null;
  sessionDate: string;
  myResult: WodResultInput | null;
};

export async function getTodayWod(userId: string): Promise<{ wod: TodayWod | null }> {
  return customFetch<{ wod: TodayWod | null }>(
    `/api/wod/today?userId=${encodeURIComponent(userId)}`,
  );
}

export async function submitWodResult(params: {
  userId: string;
  wodOfDayId: string;
  timeSeconds?: number;
  rounds?: number;
  reps?: number;
  level: WodLevel;
  notes?: string;
}): Promise<void> {
  await customFetch("/api/wod-results", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(params),
  });
}

export type WodHistoryEntry = {
  id: string;
  timeSeconds: number | null;
  rounds: number | null;
  reps: number | null;
  level: WodLevel;
  notes: string | null;
  createdAt: string;
  sessionDate: string;
  wodId: string;
  name: string;
  format: WodFormat;
};

export async function getWodHistory(userId: string): Promise<{ results: WodHistoryEntry[] }> {
  return customFetch<{ results: WodHistoryEntry[] }>(
    `/api/wod-results?userId=${encodeURIComponent(userId)}`,
  );
}
